version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: always
    ports:
      - 8080:8080
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/_health"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    restart: always
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - app_network

networks:
  app_network:
    external: true
