[package]
name = "rpc_indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.10.0"
solana-client = "1.10.0"
solana-program = "1.7.14"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
actix-web = "4.4.1"
serde_json = "1.0.111"
chrono = "0.4.31"
