[features]
seeds = false
skip-lint = false

[programs.devnet]
token_contract = "DTCrGLLNnbFZWRgwzz5WJU92q9CSkwTDbP2KWVcyGNnM"
transfers = "84REBeUeV7NN1WhSo17fW7r72QT5Fz13dbeTvm7iugox"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/phillo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
