-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."client_settings" add column "btc_exp" text
--  not null default 'mempool';
