"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/JSNQ3qsYG61
 */
import { Input } from "@/src/components/ui/input";
import { Button } from "@/src/components/ui/button";
import { useState } from "react";
import { toast } from "sonner";
import { subscribeNews } from "../actions/book";

export function Hero() {
  const [email, setEmail] = useState("");

  const onSubs = () => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!emailRegex.test(email)) {
      return toast.error("Please provide a valid email");
    }

    toast.promise(subscribeNews(email), {
      loading: "Subscribing to News letter...",
      success: ({ msg }) => {
        return "We are exicted to share updates about us...😊";
      },
      error: ({ msg }) => {
        return msg;
      },
    });
    return;
  };

  return (
    <section className="w-full z-40 py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              The future is in your wallet
            </h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Access the decentralized web with a secure and easy-to-use Web3
              wallet. Sign up to be the first to experience seamless blockchain
              integration.
            </p>
          </div>
          <div className="w-full max-w-sm space-y-2">
            <div className="flex space-x-2">
              <Input
                value={email == "" ? undefined : email}
                onChange={(e) => setEmail(e.target.value)}
                className="max-w-lg flex-1"
                placeholder="Enter your email"
                type="email"
              />
              <Button onClick={onSubs}>Sign Up</Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
