[features]
seeds = false
skip-lint = false

[programs.devnet]
token_contract = "2q1PSEpwKHp2SM6wUnEceV8jaLLpmGMxK3mnoRmduX9i"
transfers = "UdwTHQ9ag5Cvjo1ZMPg3zqTeX1aodFAtVzrnwFGZYhb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/phillo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
