[features]
seeds = false
skip-lint = false

[programs.devnet]
transfers = "AGXridxL3idGh8HJThTWciVEAAtqA7NKm7hEF5vDRJvE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/phillo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
