-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."centralized_txn" add column "baseCurrencyAmount" float8
--  not null;
