version: 0.2

env:
  secrets-manager:
    NOTIF_WORKER_PORT: "NOTIF_WORKER_PORT" 
    KAFKA_NOTIF_URL: "KAFKA_NOTIF_URL" 
    KAFKA_NOTIF_CLIENT_ID: "KAFKA_NOTIF_CLIENT_ID" 
    VAPID_PRIVATE_KEY: "VAPID_PRIVATE_KEY" 
    VAPID_PUBLIC_KEY: "VAPID_PUBLIC_KEY" 
    NOTIF_WORKER_PORT: "NOTIF_WORKER_PORT"
    HASURA_URL: "HASURA_URL"
    HAURA_ADMIN_SECRET: "HAURA_ADMIN_SECRET"
    AUTH_JWT: "AUTH_JWT"
    AUTH_JWT_PUBLIC_KEY: "AUTH_JWT_PUBLIC_KEY"
    AUTH_JWT_PRIVATE_KEY: "AUTH_JWT_PRIVATE_KEY"
    PROCESS: "PROCESS"
    TWILLO_ACCOUNT_SID: "TWILLO_ACCOUNT_SID"
    TWILLO_TOKEN: "TWILLO_TOKEN"
    TWILLO_NUMBER: "TWILLO_NUMBER"
    REDIS_SECRET: "REDIS_SECRET"
    GMAIL_APP_PASS: "GMAIL_APP_PASS"
    GMAIL: "GMAIL"
    MAIL_SERVICE: "MAIL_SERVICE"

phases:
  install:
    runtime-versions:
      nodejs: 21
  build:
    commands:
      - mv docker/notif-worker/Dockerfile .
      - cd backend/notif-worker
      - touch .env
      - printf "NOTIF_WORKER_PORT=%s\n" "$NOTIF_WORKER_PORT" >> .env
      - printf "KAFKA_NOTIF_URL=%s\n" "$KAFKA_NOTIF_URL" >> .env
      - printf "KAFKA_NOTIF_CLIENT_ID=%s\n" "$KAFKA_NOTIF_CLIENT_ID" >> .env
      - printf "VAPID_PRIVATE_KEY=%s\n" "$VAPID_PRIVATE_KEY" >> .env
      - printf "VAPID_PUBLIC_KEY=%s\n" "$VAPID_PUBLIC_KEY" >> .env
      - printf "HASURA_URL=%s\n" "$HASURA_URL" >> .env
      - printf "HAURA_ADMIN_SECRET=%s\n" "$HAURA_ADMIN_SECRET" >> .env
      - printf "AUTH_JWT=%s\n" "$AUTH_JWT" >> .env
      - printf "AUTH_JWT_PUBLIC_KEY=%s\n" "$AUTH_JWT_PUBLIC_KEY" >> .env
      - printf "AUTH_JWT_PRIVATE_KEY=%s\n" "$AUTH_JWT_PRIVATE_KEY" >> .env
      - printf "PROCESS=%s\n" "$PROCESS" >> .env
      - printf "TWILLO_ACCOUNT_SID=%s\n" "$TWILLO_ACCOUNT_SID" >> .env
      - printf "TWILLO_TOKEN=%s\n" "$TWILLO_TOKEN" >> .env
      - printf "TWILLO_NUMBER=%s\n" "$TWILLO_NUMBER" >> .env
      - printf "REDIS_SECRET=%s\n" "$REDIS_SECRET" >> .env
      - printf "GMAIL_APP_PASS=%s\n" "$GMAIL_APP_PASS" >> .env
      - printf "GMAIL=%s\n" "$GMAIL" >> .env
      - printf "MAIL_SERVICE=%s\n" "$MAIL_SERVICE" >> .env
      - cd ../..
artifacts:
  files:
    - '**/*'