version: "3"

services:
  prom-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss
    depends_on:
      - prom-server
      - loki
    ports:
      - 9095:3000
    restart: unless-stopped