name: Deploy backend-indexer

on:
  push:
    branches:
      - dev
    paths:
      - 'backend/indexer/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'backend/indexer/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "mv docker/indexer/Dockerfile ."

      - name: add secrets
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          cd backend/indexer
          touch .env
          printf 'INDEXER_PORT=%s\n' "${{secrets.INDEXER_PORT}}" >> .env
          printf 'INDEXER_KAFKA_URL=%s\n' "${{secrets.INDEXER_KAFKA_URL}}" >> .env
          printf 'INDEXER_KAFKA_ID=%s\n' "${{secrets.INDEXER_KAFKA_ID}}" >> .env
          cd ../..

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --tag shawakash/paybox-indexer:${{ github.sha }}

      - name: Docker Push
        run: docker push shawakash/paybox-indexer:${{ github.sha }}