version: 2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:

  openapi_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    open-pull-requests-limit: 10