version: 2

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    open-pull-requests-limit: 10