name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build @paybox/api Docker image
        run: docker build -t shawakash/paybox-api:latest -f ./docker/api/Dockerfile .

      - name: Push @paybox/api Docker image
        run: docker push shawakash/paybox-api:latest
